name: arpeggio
description: "An E_Commerce Guitar App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^5.0.1
  connectivity_plus: ^5.0.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  intl: ^0.19.0
  lottie: ^3.1.2
  readmore: ^3.0.0
  url_launcher: ^6.3.0
  video_player: ^2.8.7
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/Splash.png
    - assets/logo/Logo.png
    - assets/decor/Dekor_Atas.png
    - assets/banner/promo_1.png
    - assets/banner/promo_2.png
    - assets/banner/promo_3.png
    - assets/banner/promo_4.png
    - assets/product/product_1.png
    - assets/brand logo/gibson.png
    - assets/image/user_tr.png
    - assets/image/success.png
    - assets/image/DSC09683.jpg
    - assets/image/Deva.jpg
    - assets/video/VID_20240615_195428.mp4
    - assets/gif/tunggu.webp
