// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9zc757vTEy7mhaVv4jHD3qMUs11lZW90',
    appId: '1:146651058503:web:e09b279e41686cff32fc62',
    messagingSenderId: '146651058503',
    projectId: 'arpeggio-f16cd',
    authDomain: 'arpeggio-f16cd.firebaseapp.com',
    storageBucket: 'arpeggio-f16cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEXFf169Lzd9GdjjBNG73bqnvJXwcb-IA',
    appId: '1:146651058503:android:3fa3700f22cd14f932fc62',
    messagingSenderId: '146651058503',
    projectId: 'arpeggio-f16cd',
    storageBucket: 'arpeggio-f16cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_KOUh2g1aVMSnZQSAaPoEPkgbO1vcnac',
    appId: '1:146651058503:ios:10b804961d27643132fc62',
    messagingSenderId: '146651058503',
    projectId: 'arpeggio-f16cd',
    storageBucket: 'arpeggio-f16cd.appspot.com',
    androidClientId: '146651058503-o0uu9pddkuo963s2ktosidlggdjsg70r.apps.googleusercontent.com',
    iosClientId: '146651058503-0jggc3s8t691akskueld6he7irac6e6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.arpeggio',
  );

}